name: Gatsby Publish

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          GOOGLE_ANALYTICS_ID: UA-77204739-1
          BUSINESS_ID: 17841403847399914
